### ISSUE TITLE
Misspelled "repository" in image

### ISSUE THREAD

**Issue by indiamos** [learn-co-curriculum/submitting-a-lab-nitrous#6]
The word "repository" is misspelled as "rrepository" in this explanatory image:
https://curriculum-content.s3.amazonaws.com/learn-ver/nitrous_git_basics.jpg

**Comment by AnnJohn** [comment]
Thanks @indiamos for catching that.

**Comment by aviflombaum** [comment]
This lab is deprecated as we don't use nitrous so closing.
